name       : webp-pixbuf-loader
version    : 0.0.6
release    : 1
source     :
    - https://github.com/aruiz/webp-pixbuf-loader/archive/refs/tags/0.0.6.tar.gz : 451cb6924a9aa6afaa21d5b63b402dcfcfe952a1873e078b17078c4a1964a693
license    : LGPL-2.0-or-later
component  : multimedia.codecs
summary    : WebP GDK Pixbuf Loader library
description: |
    WebP Image format GdkPixbuf loader
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libwebp)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
